---
- name: WordPress with WooCommerce, Jetpack, custom theme and dummy data

  hosts: webservers
  remote_user: {{ sudo_user }}
  become: true
  vars:
    wp_advanced: true
    wp_dummy_data: true

  roles:
    - reset-wordpress
    - wordpress-install

