---
- name: Install MariaDB MySQL server
  apt: name=mariadb-server state=present update_cache=yes cache_valid_time=7200

- name: Start MariaDB MySQL Server
  service: name=mysql state=started enabled=true

- name: Set root user password
  mysql_user: name=root
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user=root
              login_password=""
              state=present

- name: Delete anonymous MySQL server user for current hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent
              login_user=root
              login_password="{{ mysql_root_password }}"

- name: Remove the test database
  mysql_db: name=test
            state=absent
            login_user=root
            login_password="{{ mysql_root_password }}"
