---
- name: Drop WordPress database
  remote_user: {{ sudo_user }}
  become: true
  mysql_db: name="{{ wordpress_db_name }}"
            state=absent
            login_user=root
            login_password="{{ mysql_root_password }}"

- name: Drop WordPress DB user
  remote_user: {{ sudo_user }}
  become: true
  mysql_user: name="{{ wordpress_db_user }}"
              state=absent
              login_user="root"
              login_password="{{ mysql_root_password }}"

- name: Remove WordPress directory
  file: path="{{ remote_wordpress_dir }}"
        state=absent
